indicators:
  - package: "github.com/hashicorp/nomad/command/agent"
    type: "s"
    function: "forward"
    indicatorType: 1
    params:
      - name: "method"
        pos: 0
  - package: "github.com/hashicorp/nomad/command/agent"
    type: "s"
    function: "forward"
    indicatorType: 1
    params:
      - name: "method"
        pos: 0
  - package: "github.com/hashicorp/nomad/api"
    type: "s"
    function: "query"
    indicatorType: 1
    params:
      - name: "endpoint"
        pos: 0

